baseURL = "https://noboru-murata.github.io/sda/"
# baseURL = "/"
disablePathToLower = true
languageCode = "en-us"
title = "統計データ解析"
theme = "docter"
publishDir = "docs"
canonifyurls = true

[params]
  # the name of your project and a link back to the home page
  home = "統計データ解析"
  # A small snippet of text above the sidebar:
  # subtitle = ""

  author = "Noboru Murata"
  author_url= "https://noboru-murata.github.io/"

  # Point readers to your repo and invite them to edit pages 
  # repo_host = "Gitlab"
  # repo = "https://gitlab.com/edavidaja/docter"

  # Add a reference to a logo, which will appear in the top right
  # logourl = ""
  # logoalt = ""

  # Mention your hosting provider 
  hosted_on = "github.com"
  hosted_on_url= "https://noboru-murata.github.io/"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["post"]
