#+TITLE: 極限定理
#+SUBTITLE: 大数の法則・中心極限定理・少数の法則
#+AUTHOR: 村田 昇
#+EMAIL: noboru.murata@eb.waseda.ac.jp
#+DATE: 2019.05.31
:preamble:
#+INCLUDE: "./myconf.org"
#+STARTUP: hidestars content
# C-c C-x C-v でinlineを切り替え
# <l C-i でlatex block
# C-c '
#+OPTIONS: LaTeX:t    
#+PROPERTY: results output
#+PROPERTY: exports both
:end:

* 基本事項の復習
** 確率変数
	- 乱数の数学的モデル: 値がランダムに決定される変数
	- 任意の区間 $[a,b]$ に含まれる確率が定められている \\
	  (数学的には厳密性を欠くが，本講義ではこの定義)
	- 確率変数 $X$ が区間 $[a,b]$ $(a\leq b)$ に含まれる確率
	  # #+begin_export latex
	  \begin{equation}
	    P(a\leq X\leq b)
	  \end{equation}
	  # #+end_export
	  (特に $a=b$ のとき $P(X=a)$ と書く)
	- 本章では有限個の値のみをとる確率変数を考える \\
	  (無限個の値，特に連続的な値については次回以降)

** 平均と分散
   - 確率変数 $X$ の取りうる値が有限個: $x_1,x_2,\dotsc,x_N$
   - *平均* もしくは *期待値*
     # #+begin_export latex
     \begin{equation}
       \mathbb{E}[X]:=\sum_{i=1}^Nx_iP(X=x_i)
     \end{equation}
     # #+end_export
   - *分散* ($=\text{標準偏差}^{2}$)
     # #+begin_export latex
     \begin{equation}
       \mathrm{Var}(X)
       :=\mathbb{E}[(X-\mathbb{E}[X])^2]
       % =\sum_{i=1}^N(x_i-\mathbb{E}[X])^2P(X=x_i)\\
       =\mathbb{E}[X^2]-\mathbb{E}[X]^2
     \end{equation}
     # #+end_export

** 演習
   :PROPERTIES:
   :reveal_background: #fef4f4
   :END:
   - 確率変数 $X$: \\
     偶数の出る確率が奇数の2倍のサイコロの目
     # #+begin_export latex
     \begin{align*}
       &P(X=1)=P(X=3)=P(X=5)=1/9\\ 
       &P(X=2)=P(X=4)=P(X=6)=2/9
     \end{align*}
     # #+end_export
   - $X$ の平均と分散は?
   
** 解答 (計算例)
   - $X$ の平均は
     # #+begin_export latex
     \begin{equation}
       \mathbb{E}[X]=\sum_{x=1}^6xP(X=x)
       ={11}/{3}=3.6666\dots
     \end{equation}
     # #+end_export
   - $X$ の分散は
     # #+begin_export latex
     \begin{align}
       \mathbb{E}[X^2]&=\sum_{x=1}^6x^2P(X=x)={49}/{3}\\
       \mathrm{Var}(X)&={49}/{3}-{121}/{9}={26}/{9}=2.88\dots
     \end{align}
     # #+end_export

* 独立性と同分布性
** データの統計的性質
   - 統計的な枠組: 観測データの一つ一つが確率変数
   - 確率変数の列 $X_1,X_2,\dotsc,X_n$ に対する考察が重要
   - 「 $X_1$ が $x_1$ という値をとり，
     $X_2$ が $x_2$ という値をとり， $\dots$ ，
     $X_n$ が $x_n$ という値をとる」という事象が起きる確率:
     *同時分布*
     # #+begin_export latex
     \begin{equation}
       P(X_1=x_1,X_2=x_2,\dots,X_n=x_n)
     \end{equation}
     # #+end_export

** 独立性
   - 無関係にサンプリングされた観測データ
   - 確率変数列 $X_1,X_2,\dotsc,X_n$ が *独立* であるとは，
     任意の $n$ 個の実数 $x_1,x_2,\dotsc,x_n$ に対して
     # #+begin_export latex
     \begin{multline}
       P(X_1=x_1,X_2=x_2,\dotsc,X_n=x_n)\\
       =P(X_1=x_1)\cdot P(X_2=x_2)\cdots P(X_n=x_n)
     \end{multline}
     # #+end_export
     が成り立つことをいう
     # 直感的には
     # すべての$i=1,\dots,n$について,
     # $X_i$がとる値は$X_1,\dotsc,X_{i-1},X_{i+1},\dotsc,X_n$がとる値と無関係に定まるということ

** 同分布性
   - 同一の法則に従って生成された観測データ
   - 確率変数列 $X_1,X_2,\dotsc,X_n$ が *同分布* であるとは，
     任意の実数 $x$ に対して
     # #+begin_export latex
     \begin{equation}
       P(X_1=x)=P(X_2=x)=\cdots=P(X_n=x)
     \end{equation}
     # #+end_export
     が成り立つことをいう

** 独立同分布性
   - 一般に分析対象のデータには
     *独立性* と *同分布性* 
     が同時に仮定される
   - 独立かつ同分布な確率変数列を
     *独立同分布*
     もしくは
     *i.i.d.* 
    であるという\\
    (i.i.d.はindependent and identically distributedの略)

* 大数の法則
** 大数の法則の概要
   - 同一の法則に従って生成された集団から
     *ランダムな* 観測を多数繰り返すと，
     観測値の平均は「真の平均値」に近づく
     # % 分析対象の一部を\alert{ランダムに}収集したデータのみを用いて(標本)平
     # % 均を計算しても, データのサンプル数が十分大きければ, その平均値は集団
     # % 全体の平均値に近い値であると考えられることは, 経験則としてよく知られ
   - 具体的な例: 
     - 歪みの無いコインの表が出た回数の割合
     - 視聴率の調査
   - この法則を数学的に定式化した定理が *大数の法則*

** 無限列の独立性と同分布性
   - $X_1,X_2,\dotsc$ が *独立* であるとは，
     任意の正整数 $n$ に対して $X_1,X_2,\dotsc,X_n$ が
     独立であることをいう
   - $X_1,X_2,\dotsc$ が *同分布* であるとは，
     任意の正整数 $n$ に対して $X_1,X_2,\dotsc,X_n$ が
     同分布であることをいう
   - $X_1,X_2,\dotsc$ が *独立同分布*
     もしくは *i.i.d.* であるとは，
     $X_1,X_2,\dotsc$ が独立かつ同分布であることをいう

** 大数の強法則
   $X_1,X_2,\dotsc$ を独立同分布な確率変数列とし，
   その平均を $\mu$ とする．
   このとき,  $X_1,\dotsc,X_n$ の標本平均
   # #+begin_export latex
   \begin{equation}
     \bar{X}_n := \frac{1}{n}\sum_{i=1}^nX_i
   \end{equation}
   # #+end_export
   が $n\to\infty$ のとき $\mu$ に収束する確率は1である．
   このことを「 $\bar{X}_{n}$ は
   $n\to\infty$ のとき $\mu$ に *概収束* する」という．

** 演習
   :PROPERTIES:
   :reveal_background: #fef4f4
   :END:
   大数の法則の実行例 ~mc-lln.r~ において，
   乱数のシード値・出現確率の変更・乱数の変更などを行っても
   大数の法則が成立することを確認せよ． \\
   また，サンプル数の増減によって精度がどの程度変わるか観察せよ．

* 中心極限定理
** 中心極限定理の概要
   - 大数の法則の主張: 
     - $n$ を大きくすると標本平均 $\bar{X}_n$ は真の平均 $\mu$ に近づく
     - 推定誤差 $\bar{X}_n-\mu$ は $n$ を大きくすると0に近づく
     - どの程度の大きさになるのか定量的な評価は与えていない
   - 誤差の評価の定量化:
     - 推定誤差がある区間 $[\alpha,\beta]$ に入る確率で定量的に評価可能
       # #+begin_export latex
       \begin{equation}
	 P(\alpha\leq \bar{X}_n-\mu\leq \beta)
       \end{equation}
       # #+end_export
     - 上式の正確な計算は一般には困難
   - サンプル数が大きい場合の定量的な評価の近似方法を述べたのが *中心極限定理*

** 中心極限定理
   $X_1,X_2,\dotsc$ を独立同分布な確率変数列とし，
   その平均を $\mu$ ，標準偏差を $\sigma$ とする．
   このとき，すべての実数 $a < b$ に対して
   # #+begin_export latex
   \begin{equation}
     P\Bigl(a\leq\frac{\sqrt{n}(\bar{X}_n-\mu)}{\sigma}\leq b \Bigr)
     \to\frac{1}{\sqrt{2\pi}}\int_a^be^{-\frac{x^2}{2}}dx\quad
     (n\to\infty)
   \end{equation}
   # #+end_export
   が成り立つ．

** 中心極限定理の意味
   - $X_i$ の分布が何であっても，
     サンプル数 $n$ が十分大きければ，
     標本平均を正規化した量の $\sqrt{n}(\bar{X}_n-\mu)/\sigma$ の分布は，
     標準正規確率分布で近似できる
   - 正規化した誤差は，
     サンプル数 $n$ が十分大きければ *標準正規分布*
     # #+begin_export latex
     \begin{equation}
       P\Bigl(a\frac{\sigma}{\sqrt{n}}\leq\bar{X}_n-\mu\leq
       b\frac{\sigma}{\sqrt{n}} \Bigr)
       \simeq
       \frac{1}{\sqrt{2\pi}}\int_a^be^{-\frac{x^2}{2}}dx
     \end{equation}
     # #+end_export
     で近似できる\\
     被積分関数$\phi(x)=\frac{1}{\sqrt{2\pi}}e^{-\frac{x^2}{2}}$
     を *標準正規密度* という

** 数値シミュレーションの設計
   - $\sqrt{n}(\bar{X}_n-\mu)/\sigma$ の分布と
     標準正規分布を比較する
   - 中心極限定理が正しければ，
     十分小さいビン $[a,b]$ におけるヒストグラムの高さは $\phi(a)$ で近似できる
   - $\sqrt{n}(\bar{X}_n-\mu)/\sigma$ のヒストグラムに
     標準正規密度 $\phi(x)$ を重ね書きすることで近似の度合いを評価できる
   - 密度表示は ~hist()~ で ~freq=FALSE~ に指定する
   - 標準正規密度 $\phi(x)$ は ~dnorm()~ で計算する
     # $\phi(x)=\frac{1}{\sqrt{2\pi}}e^{-\frac{x^2}{2}}$

** 演習
   :PROPERTIES:
   :reveal_background: #fef4f4
   :END:
   中心極限定理の実行例 ~mc-clt.r~ において，
   乱数のシード値・出現確率の変更・乱数の変更などを行っても
   中心極限定理が成立することを確認せよ． \\
   また，サンプル数の増減によって精度がどの程度変わるか観察せよ．

* 少数の法則
** 少数の法則の概要
   - 滅多に起きない事が起こる回数の分布に関する法則
   - 典型的な例:
     - ある製品の不良品率 $p$ はとても小さいとする
     - 一日に $n$ 個(非常に多数とする)生産するとき，
       不良品は平均的には $\lambda=np$ 個発生するが，
       日によって不良品の個数 $S_n$ には多少のばらつきが生じる
     - 個数 $S_n$ は確率変数であるが，
       $S_n$ がとる値の確率法則は？
     - 強度 $\lambda$ の *Poisson分布* で近似できることが知られている
   - これを正確に述べたのが *少数の法則*

** 少数の法則
   $X_1,X_2,\dotsc,X_n$ を独立な確率変数列とし，
   各 $i=1,2,\dotsc,n$ について $X_i$ は確率 $p_{n,i}$ で1を，
   確率 $1-p_{n,i}$ で0をとるとする:
   # #+begin_export latex
   \begin{align}
     &P(X_i=1)=p_{n,i},\\
     &P(X_i=0)=1-p_{n,i}\quad
     (i=1,2,\dots,n).
   \end{align}
   # #+end_export

** 少数の法則 (つづき)
   このとき, ある正の実数 $\lambda$ が存在して, $n\to\infty$ のとき
   # #+begin_export latex
   \begin{equation}
     \max_{i=1,2,\dots,n}p_{n,i}\to0,\quad
     \sum_{i=1}^np_{n,i}\to\lambda
   \end{equation}
   # #+end_export
   ならば，任意の整数 $k\geq0$ に対して以下が成り立つ:
   # #+begin_export latex
   \begin{equation}
     P\Bigl(\sum_{i=1}^nX_i=k\Bigr)
     \to e^{-\lambda}\frac{\lambda^k}{k!}
     \quad(n\to\infty).
   \end{equation}
   # #+end_export

** 補足
   - 定理の $\sum_{i=1}^nX_i$ が不良品の例の $S_n$ に対応する
   - 確率変数の取りうる値が0以上の整数全体で，
     値が整数 $k\geq0$ となる確率が
     # #+begin_export latex
     \begin{equation}
       e^{-\lambda}\frac{\lambda^k}{k!}
     \end{equation}
     # #+end_export
     で与えられるものを，
     強度 $\lambda$ の *Poisson型確率変数* と呼び，
     その確率法則を強度 $\lambda$ のPoisson分布と呼ぶ
   - Poisson分布の確率の値は ~dpois()~ で計算できる

** 演習
   :PROPERTIES:
   :reveal_background: #fef4f4
   :END:
   少数の法則の実行例 ~mc-lsn.r~ において，
   乱数のシード値を変更しても少数の法則が成立することを確認せよ． \\
   また，パラメータ $n,p$ の変更によって
   結果がどのように変わるか観察せよ．

* 補遺・重複対数の法則
** 重複対数の法則
   $X_1,X_2,\dotsc$ を独立同分布な確率変数列とし，
   その平均を $\mu$ ，標準偏差を $\sigma$ とする．
   このとき
   # #+begin_export latex
   \begin{align}
     &\limsup_{n\to\infty}
       \frac{\sqrt{n}(\bar{X}_{n}-\mu)}
       {\sqrt{2\sigma^2\log\log n}}
       =1\quad\text{a.s.},\\
     &\liminf_{n\to\infty}
       \frac{\sqrt{n}(\bar{X}_{n}-\mu)}
       {\sqrt{2\sigma^2\log\log n}}
       =-1\quad\text{a.s.}
   \end{align}
   # #+end_export
   が成り立つ．

** Hartman-Wintnerの定理
   前定理の条件のもと，列
   # #+begin_export latex
   \begin{equation}
     \Bigl(\frac{\sqrt{n}(\bar{X}_{n}-\mu)}
       {\sqrt{2\sigma^2\log\log n}}\Bigr)_{n=3}^\infty
   \end{equation}
   # #+end_export
   のある部分列の収束先となるような実数全体の集合を $C$ とすると，
   $C$ が閉区間 $[-1,1]$ に一致する確率は1である. 

** 演習
   :PROPERTIES:
   :reveal_background: #fef4f4
   :END:
   重複対数の法則の実行例 ~mc-lil.r~ において，
   乱数のシード値・出現確率の変更・乱数の変更などを行っても
   重複対数の法則が成立することを確認せよ． \\
   また，サンプル数の増減によって精度がどの程度変わるか観察せよ．

